import { addDays, format } from "date-fns";
import type { Task, TaskList } from "./types";

function iso(offset: number): string {
  return format(addDays(new Date(), offset), "yyyy-MM-dd");
}

const now = Date.now();

export const DEFAULT_LIST_ID = "tasks";

export const SEED_LISTS: TaskList[] = [
  { id: DEFAULT_LIST_ID, name: "任务", createdAt: now - 86400000 * 10, locked: true },
  { id: "work", name: "工作", createdAt: now - 86400000 * 8 },
  { id: "personal", name: "个人", createdAt: now - 86400000 * 7 },
  { id: "shopping", name: "购物", createdAt: now - 86400000 * 3 },
];

export const SEED_TASKS: Task[] = [
  {
    id: "t1",
    listId: "work",
    title: "整理本周进度并写纪要",
    notes: "把未关闭的事项标出负责人，下午三点前发出。",
    completed: false,
    important: true,
    myDay: true,
    dueDate: iso(0),
    steps: [
      { id: "t1s1", title: "汇总未完成项", completed: true },
      { id: "t1s2", title: "起草纪要", completed: false },
      { id: "t1s3", title: "发给相关同事", completed: false },
    ],
    createdAt: now - 3600000 * 30,
    completedAt: null,
  },
  {
    id: "t2",
    listId: "work",
    title: "回复供应商询价邮件",
    notes: "",
    completed: false,
    important: false,
    myDay: true,
    dueDate: iso(0),
    steps: [],
    createdAt: now - 3600000 * 20,
    completedAt: null,
  },
  {
    id: "t3",
    listId: "work",
    title: "核对实验记录表",
    notes: "对照原始数据，标出异常点。",
    completed: false,
    important: true,
    myDay: false,
    dueDate: iso(1),
    steps: [],
    createdAt: now - 3600000 * 48,
    completedAt: null,
  },
  {
    id: "t4",
    listId: "work",
    title: "预约下周机时",
    notes: "",
    completed: false,
    important: false,
    myDay: false,
    dueDate: iso(3),
    steps: [],
    createdAt: now - 3600000 * 10,
    completedAt: null,
  },
  {
    id: "t5",
    listId: "personal",
    title: "晚上散步 30 分钟",
    notes: "",
    completed: false,
    important: false,
    myDay: true,
    dueDate: iso(0),
    steps: [],
    createdAt: now - 3600000 * 6,
    completedAt: null,
  },
  {
    id: "t6",
    listId: "personal",
    title: "给家里打电话",
    notes: "",
    completed: false,
    important: true,
    myDay: false,
    dueDate: iso(2),
    steps: [],
    createdAt: now - 3600000 * 40,
    completedAt: null,
  },
  {
    id: "t7",
    listId: "personal",
    title: "预约年度体检",
    notes: "工作日上午更容易约上。",
    completed: false,
    important: false,
    myDay: false,
    dueDate: iso(7),
    steps: [],
    createdAt: now - 3600000 * 72,
    completedAt: null,
  },
  {
    id: "t8",
    listId: "shopping",
    title: "咖啡豆",
    notes: "",
    completed: false,
    important: false,
    myDay: false,
    dueDate: null,
    steps: [],
    createdAt: now - 3600000 * 5,
    completedAt: null,
  },
  {
    id: "t9",
    listId: "shopping",
    title: "打印纸和签字笔",
    notes: "",
    completed: false,
    important: false,
    myDay: false,
    dueDate: iso(-1),
    steps: [],
    createdAt: now - 3600000 * 50,
    completedAt: null,
  },
  {
    id: "t10",
    listId: "work",
    title: "更新项目文件夹结构",
    notes: "",
    completed: true,
    important: false,
    myDay: false,
    dueDate: iso(-2),
    steps: [],
    createdAt: now - 3600000 * 90,
    completedAt: now - 3600000 * 8,
  },
  {
    id: "t11",
    listId: DEFAULT_LIST_ID,
    title: "把书桌收拾干净",
    notes: "",
    completed: false,
    important: false,
    myDay: false,
    dueDate: null,
    steps: [],
    createdAt: now - 3600000 * 12,
    completedAt: null,
  },
];
